import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/Header/Header'
import NavBar from '../components/NavBar/NavBar'
import Result from '../components/Result/Result'
import requests from '../utils/request'

export default function Home({results}) {
  
  return (
    <div>
      <Head>
        <title> HULU 2.0 </title>{' '}
        <meta
          name='cloning facebook with nextjs'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>{' '}
      <Header />
      <NavBar />
      <Result results={results} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchActionMovie.url}`
  ).then((res) => res.json())

  // const allRequest = JSON.stringify(request)

  return {
    props: {
      results: request.results
    },
  }
}
